// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZeGwx6Y64jN1F3r0ordnGr0Lg49yhm8M',
    appId: '1:901511422350:web:1846335232e6a0b54c04df',
    messagingSenderId: '901511422350',
    projectId: 'patiyuvaaa',
    authDomain: 'patiyuvaaa.firebaseapp.com',
    storageBucket: 'patiyuvaaa.appspot.com',
    measurementId: 'G-YK8ZQGMYJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuqD5orqjjuPvjU0Sw_qfuFHEKPzx8aTQ',
    appId: '1:901511422350:android:39c0f98b7b54b4624c04df',
    messagingSenderId: '901511422350',
    projectId: 'patiyuvaaa',
    storageBucket: 'patiyuvaaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe3h-AdRkfo42mwa1YhTn0xJ6A2hiVr2o',
    appId: '1:901511422350:ios:5e6cda4b4591f8ae4c04df',
    messagingSenderId: '901511422350',
    projectId: 'patiyuvaaa',
    storageBucket: 'patiyuvaaa.appspot.com',
    iosBundleId: 'com.example.patiYuvaa',
  );

}